# Auto-generate Ansible inventory from Terraform outputs

resource "local_file" "ansible_inventory" {
  filename = "../ansible/inventory/hosts.yml"

  content = <<-EOT
---
all:
  children:
    frontend:
      hosts:
        frontend-instance:
          ansible_host: ${aws_instance.frontend.public_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/${var.key_pair_name}.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    backend:
      hosts:
        backend-instance:
          ansible_host: ${aws_instance.backend.private_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/${var.key_pair_name}.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=frontend-instance'

    database:
      hosts:
        db-instance:
          ansible_host: ${aws_instance.database.private_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/${var.key_pair_name}.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyJump=frontend-instance'
EOT

  file_permission = "0644"
}

# Also generate group_vars with all necessary variables
resource "local_file" "ansible_group_vars" {
  filename = "../ansible/group_vars/all.yml"

  content = <<-EOT
---
# Auto-generated by Terraform
frontend_ip: ${aws_instance.frontend.public_ip}
backend_ip: ${aws_instance.backend.private_ip}
database_ip: ${aws_instance.database.private_ip}

# Docker Hub username
dockerhub_username: "YOUR_DOCKERHUB_USERNAME"

# Image versions
vote_image_tag: "latest"
result_image_tag: "latest"
worker_image_tag: "latest"
redis_image_tag: "alpine"
postgres_image_tag: "15-alpine"

# Database credentials
postgres_user: "postgres"
postgres_password: "postgres"
postgres_db: "postgres"

# Redis configuration
redis_host: "${aws_instance.backend.private_ip}"
redis_port: 6379

# PostgreSQL configuration
postgres_host: "${aws_instance.database.private_ip}"
postgres_port: 5432

# Application ports
vote_port: 80
result_port: 5001
EOT

  file_permission = "0644"
}
