# Auto-generate Ansible inventory from Terraform outputs
resource "local_file" "ansible_inventory" {
  content = templatefile("${path.module}/templates/ansible_inventory.tpl", {
    frontend_public_ip  = aws_instance.frontend.public_ip
    frontend_private_ip = aws_instance.frontend.private_ip
    backend_private_ip  = aws_instance.backend.private_ip
    db_private_ip       = aws_instance.database.private_ip
    ssh_key_path        = "~/.ssh/${var.key_pair_name}.pem"
  })

  filename        = "${path.module}/../ansible/inventory/hosts.yml"
  file_permission = "0644"
}

# Auto-generate SSH config for bastion access
resource "local_file" "ssh_config" {
  content = templatefile("${path.module}/templates/ssh_config.tpl", {
    frontend_public_ip = aws_instance.frontend.public_ip
    backend_private_ip = aws_instance.backend.private_ip
    db_private_ip      = aws_instance.database.private_ip
    ssh_key_path       = "~/.ssh/${var.key_pair_name}.pem"
  })

  filename        = "${path.module}/../ansible/ssh_config"
  file_permission = "0644"
}

# Generate Ansible variables file with connection details
resource "local_file" "ansible_connection_vars" {
  content = <<-EOT
---
# Auto-generated by Terraform - DO NOT EDIT MANUALLY
# Generated: ${timestamp()}

# IP Addresses
frontend_public_ip: "${aws_instance.frontend.public_ip}"
frontend_private_ip: "${aws_instance.frontend.private_ip}"
backend_private_ip: "${aws_instance.backend.private_ip}"
database_private_ip: "${aws_instance.database.private_ip}"

# Connection settings
redis_host: "${aws_instance.backend.private_ip}"
postgres_host: "${aws_instance.database.private_ip}"
redis_port: 6379
postgres_port: 5432

# Instance details
frontend_instance_id: "${aws_instance.frontend.id}"
backend_instance_id: "${aws_instance.backend.id}"
database_instance_id: "${aws_instance.database.id}"

# VPC details
vpc_id: "${aws_vpc.time_circuit.id}"
public_subnet_id: "${aws_subnet.townsquare_public.id}"
private_subnet_id: "${aws_subnet.lab_private.id}"
EOT

  filename        = "${path.module}/../ansible/group_vars/terraform_generated.yml"
  file_permission = "0644"
}

# Output instructions for the user
output "ansible_setup_complete" {
  value = <<-EOT

  ========================================
  🎉 Ansible Configuration Auto-Generated!
  ========================================

  Files created:
  ✅ ansible/inventory/hosts.yml
  ✅ ansible/group_vars/terraform_generated.yml
  ✅ ansible/ssh_config

  Next steps:
  1. Update your Docker Hub username:
     nano ansible/group_vars/all.yml

  2. (Optional) Copy SSH config to your home directory:
     cat ansible/ssh_config >> ~/.ssh/config

  3. Test Ansible connectivity:
     cd ansible && ansible all -m ping

  4. Deploy!
     ansible-playbook playbooks/install-docker.yml
     ansible-playbook playbooks/deploy-all.yml

  Access your apps:
  Vote:   http://${aws_instance.frontend.public_ip}:80
  Result: http://${aws_instance.frontend.public_ip}:5001
  ========================================
  EOT
}
