---
# Auto-generated by Terraform - DO NOT EDIT MANUALLY
# Any changes will be overwritten on next terraform apply

all:
  children:
    frontend:
      hosts:
        frontend-instance:
          ansible_host: ${frontend_public_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${ssh_key_path}
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      vars:
        redis_host: ${backend_private_ip}
        postgres_host: ${db_private_ip}

    backend:
      hosts:
        backend-instance:
          ansible_host: ${backend_private_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${ssh_key_path}
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${frontend_public_ip}'
      vars:
        redis_host: ${backend_private_ip}
        postgres_host: ${db_private_ip}

    database:
      hosts:
        db-instance:
          ansible_host: ${db_private_ip}
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ${ssh_key_path}
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyJump=ubuntu@${frontend_public_ip}'
